nada_cols = [
  'SLK'
,'RowKey'
,'Program'
,'Staff'
# ,'AssessmentType' # initial -> SurveyStatge  = 0 (progress)
,'AssessmentDate'

,'K5_Score'


# ,'disability'
# ,'AODConcerns'
# ,'OtherLifeIssues'
# ,'HaveDVOrFamilySafetyConcerns'


# ,'Values' -- whats this

,'K5Q2'
,'K5Q3'
,'K5Q5'
,'K5Q4'

,'K10Q01'
,'K10Q02'
,'K10Q03'
,'K10Q04'
,'K10Q05'
,'K10Q06'
,'K10Q07'
,'K10Q08'
,'K10Q09'
,'K10Q10'
,'K10Q11'
,'K10Q12'
,'K10Q13'
,'K10Q14'  # 43    Q14. In the last four weeks, how often have physical health problems been the main cause of these feelings?

#,'question1'  ## ----------------------------

,'K10_Score'
,'SDS_Score'
# ,'CDS5_Score'

# ,'HaveYouEverInjected'
# ,'HowLongSinceLastInjected'
# ,'HaveYouEverSharedEquipment'
# 57. BBV 4.1 BBV Injecting drug use (BTOM) Number 1 58. BBV 4.2 BBV Sharing of needle and syringe (BTOM) Number 1 59. BBV 4.3 BBV Sharing other injecting equipment (BTOM)

# ,'DoYouSmoke'
# ,'TobaccoAsSpin'

# ,'DoYouFeelSafeWhereYouLive'


# ,'HowOftenNegativeFeelings'
,'Past4WkHadCaregivingResponsibilities' # 154. ATOP 2Eii  # 1 yes 0 no -1 not answered/no answer
,'Past4WkBeenArrested'
# ,'HowCloseToManagingSubstanceUse'
# ,'HowSatisfiedWithProgress'
# ,'SupportTypeBestMatchesNeedsGoals'


,'Past4WkNumInjectingDays'

,'SDSIsAODUseOutOfControl'
,'SDSDoesMissingFixMakeAnxious'
,'SDSHowMuchDoYouWorryAboutAODUse'
,'SDSDoYouWishToStop'             #15    Q4/
,'SDSHowDifficultToStopOrGoWithout'  # 16     Q5. How difficult would you/did you find it to stop or go without?

# ,'Past4WkAodRisks'
# ,'Past4WkDailyLivingImpacted'  -----  QoL ? ?

# ,'SetBoundariesPrioritiseWellbeing'
# ,'Past4WkDifficultyFindingHousing'             NOT 152. ATOP 2D  Has the client been at risk of eviction over the past four weeks?
# ,'ChildProtectionDetails'

,'Past4WkUseLedToProblemsWithFamilyFriend'
,'Past4WkHowOftenPhysicalHealthCausedProblems'
,'Past4WkHowOftenMentalHealthCausedProblems'
,'Past4WkHowOftenIllegalActivities'

,'Past4WkEngagedInOtheractivities.Paid Work'     # 143. ATOP 2A.2 ATOP Days Paid Work Total
,'Past4WkEngagedInOtheractivities.Voluntary Work'
,'Past4WkEngagedInOtheractivities.Study - college, school or vocational education'   # 149. ATOP 2B.2 he total number of days of school or study in the past four weeks.

,'PrimaryCaregiver'  # ? 153 ? ATOP 2Ei Primary Caregiver Under 5 Has the client at any time in the past four weeks, been a primary care giver for or living with any child/children aged under 5 years?
,'Past4WkEngagedInOtheractivities.Looking after children'  # ? 153 ? ATOP 2Ei Primary Caregiver Under 5 Has the client at any time in the past four weeks, been a primary care giver for or living with any child/children aged under 5 years?
            #154  Primary Caregiver 5 to15 Has the client at any time in the past four weeks, been a primary care giver for or living with any child/children aged under 5 years?

,'Past4WkEngagedInOtheractivities.Other caregiving activities'


,'AreYouAccessingOtherServices'
,'WhenMentalHealthDiagnosis'

# ,'Relationship'
# ,'ManagingImpact'
,'LegalIssuesDueToOthersUse'
,'HowCloseToManagingImpactOfOthersUse'


# ,'ReferredFrom'
# ,'DiversityList'


          # 61.  ND 5.1 ND Do you smoke tobacco?
          # ND How soon after waking do you smoke your first cigarette? 
          # 63. ND 5.3 ND How many cigarettes smoked on a typical day?
          #   64. ND 5.4 ND If previously attempted to quit, withdrawals or cravings experienced?

# ,'CDS5RateAddictiontoCigarettes'
          
# ,'MotivationtoQuit'
# ,'HowLongSmoked'
# ,'ConfidentQuittingReducing'
# ,'HowManyTimesQuitSmoking'
# ,'HowManagingQuitting'
# ,'HowMuchDoYouKnow'
# ,'QuitlineReferral'
# ,'InterventionType'
# ,'ManagingQuitting'
# ,'CurrentlySmokeYN'
# ,'QuitSmokingBeforeYN'

# ,'IncomeSource'
# ,'CanYouBudgetYN'
# ,'AffordabilityYN'
# ,'ManagingPH'
# ,'PTOYN'
# ,'ManagingMH'
# ,'MHStrategies'
# ,'ChildrenYN'
,'Alcohol_PerOccassionUse'
,'Alcohol_DaysInLast28'
,'Heroin_PerOccassionUse'
,'Heroin_DaysInLast28'
,'Other Opioids_PerOccassionUse'
,'Other Opioids_DaysInLast28'
,'Cocaine_PerOccassionUse'
,'Cocaine_DaysInLast28'
,'Cannabis_PerOccassionUse'
,'Cannabis_DaysInLast28'  # 77. ATOP 1B.3   Cannabis Total (past 4 weeks)
,'Amphetamines_PerOccassionUse'
,'Amphetamines_DaysInLast28'
,'Tranquilliser_PerOccassionUse'
,'Tranquilliser_DaysInLast28'
,'Another Drug_PerOccassionUse'
,'Another Drug_DaysInLast28'
,'Nicotine_PerOccassionUse'
,'Nicotine_DaysInLast28'
# ,'Gambling_PerOccassionUse'
# ,'Gambling_DaysInLast28'


,'Past4WkHaveYouViolenceAbusive'  #156.  ATOP 2G  ATOP Violent To You Has anyone been violent (incl. domestic violence) towards the client in past four weeks?
         ## or is it:  157 ATOP 2H Violent To Others Has the client been violent (incl. domestic violence) towards someone else in the past four weeks? ???????????????????????????


,'Past4WkMentalHealth' #158  ATOP 2 I Psychological Health Status Client’s rating of their psychological wellbeing in past four weeks (anxiety, depression, problems with emotions and feelings) 0=poor 10=good
,'Past4WkPhysicalHealth'  # 159. ATOP 2J Physical Health Status Client’s rating of their physical health in past 4 weeks (extent of physical symptoms and bothered by illness)
,'Past4WkQualityOfLifeScore'  # 160.  ATOP 2K Qual of life  

]

# ,'ManagingRelations'
# ,'ReportingRequirementsYN'
# ,'BailConditionsYN'
# ,'CorrectiveServsApptsYN'
# ,'IncarceratedAMCYN'
# ,'CriminalRecordYN'
# ,'AVOorFVOYN'
# ,'ICOYN'
# ,'CSO'
# ,'PublicTrusteeYN'

# ,'OtherLegalIssuesYN'
# ,'WhereAreYouAt'
# ,'AssistAccessOtherServicesYN'
# ,'ChangeActivities.SelfReflection'
# ,'ChangeActivities.ManagingEmotions'
# ,'ChangeActivities.HealthLiving'
# ,'ChangeActivities.LifestyleChanges'
# ,'ChangeActivities.LifeWithout'
# ,'ChangeActivities.ManageSubstance'
# ,'HealthChecklist_STAFF'

# ,'question5'  ##-------------------------
# ,'question4'  ##  whats this
# ,'WhatToWorkOn2'
# ,'SatisfiedwithProgress2' why 2 ? 
# ,'ChildCustody'
# ,'FamilyCourtOrdersYN'
# ,'SupervisedVisitYN'
# ,'ConnectionToServices'
# ,'CourtDatesYN'
# ,'OtherAddictiveBehaviours.Others'
# ,'OtherAddictiveBehaviours.Gaming'
# ,'OtherAddictiveBehaviours.Sex'
# ,'OtherAddictiveBehaviours.Hoarding'
# # ,'Past4WkAnyOtherAddictiveB'
# ,'OtherAddictiveBehaviours.Gambling'





# all_cols = ['SLK'
# ,'RowKey'
# ,'Program'
# ,'Staff'
# ,'SurveyName'
# ,'AssessmentDate'
# ,'CCareID'
# ,'ClientType'
# ,'IARDST'
# ,'IndigenousStatus'
# ,'<18'
# ,'Past4WkMentalHealth'
# ,'WhyHereToday'
# ,'EverDiagnosedMentalHealthIssue'
# ,'MentalHealthHistory'
# ,'AnythingelseMH'
# ,'MHRecentRiskIssues'
# ,'MHHistoricalRiskIssues'
# ,'K5_Score'
# ,'DoSDQ'
# ,'SDQPDifficultiesScore'
# ,'SDQPConductProblemsScore'
# ,'SDQPPeerProblemsScore'
# ,'SDQPEmotionalProblemsScore'
# ,'SDQPHyperactivityScore'
# ,'SDQPProsocialScore'
# ,'QPR_ScoreOrig'
# ,'MentalIssues'
# ,'PhysicalHealthConcerns'
# ,'Past4WkPhysicalHealth'
# ,'disability'
# ,'AODConcerns'
# ,'OtherLifeIssues'
# ,'HaveDVOrFamilySafetyConcerns'
# ,'Past4WkHaveYouViolenceAbusive'
# ,'Past4WkQualityOfLifeScore'
# ,'Whatsuseful'
# ,'Strengthsabilities'
# ,'Values'
# ,'HaveAnySocialSupport'
# ,'HaveOtherSupports'
# ,'WhatToWorkOn1'
# ,'WhyisitChallenging1'
# ,'Possibilities1'
# ,'WhatCouldGetInTheWay1'
# ,'SatisfiedwithProgress1'
# ,'WhatToWorkOn3'
# ,'WhyisitChallenging3'
# ,'Possibilities3'
# ,'WhatCouldGetInTheWay3'
# ,'SatisfiedwithProgress3'
# ,'K10Q01'
# ,'K10Q02'
# ,'K10Q03'
# ,'K10Q04'
# ,'K10Q05'
# ,'K10Q06'
# ,'K10Q07'
# ,'K10Q08'
# ,'K10Q09'
# ,'K10Q10'
# ,'K10Q12'
# ,'K10Q14'
# ,'QPRQ1'
# ,'QPRQ2'
# ,'QPRQ3'
# ,'QPRQ4'
# ,'QPRQ5'
# ,'QPRQ6'
# ,'QPRQ7'
# ,'QPRQ8'
# ,'QPRQ9'
# ,'QPRQ10'
# ,'QPRQ11'
# ,'QPRQ12'
# ,'QPRQ13'
# ,'question1'
# ,'QPRQ15'
# ,'PDC'
# ,'Anyodc'
# ,'ODC'
# ,'K10_Score'
# ,'QPR_Score'
# ,'K10Q13'
# ,'SDS_Score'
# ,'CDS5_Score'
# ,'HaveYouEverInjected'
# ,'HowLongSinceLastInjected'
# ,'HaveYouEverSharedEquipment'
# ,'DoYouSmoke'
# ,'TobaccoAsSpin'
# ,'Past4WkAnyOtherAddictiveB'
# ,'HowDoYouSpendTime'
# ,'PrioritiseCare'
# ,'DoYouFeelSafeWhereYouLive'
# ,'Past4WkBeenHospCallAmbulance'
# ,'AreYouCurrentlyTakingMeds'
# ,'HowOftenNegativeFeelings'
# ,'Past4WkHadCaregivingResponsibilities'
# ,'Past4WkBeenArrested'
# ,'HowCloseToManagingSubstanceUse'
# ,'HowSatisfiedWithProgress'
# ,'SupportTypeBestMatchesNeedsGoals'
# ,'FinalChecklist'
# ,'AssessmentType'
# ,'doK10'
# ,'Past4WkNumInjectingDays'
# ,'SDSIsAODUseOutOfControl'
# ,'SDSDoesMissingFixMakeAnxious'
# ,'SDSHowMuchDoYouWorryAboutAODUse'
# ,'SDSHowDifficultToStopOrGoWithout'
# ,'SDSDoYouWishToStop'
# ,'MotivationToQuit'
# ,'CDS5HowSoonAfterWaking'
# ,'CDS5HowManyCigarettesPerDay'
# ,'CDS5HowHardIsQuitting'
# ,'CDS5HowStrongTheUrgeToSmoke'
# ,'Past4WkAodRisks'
# ,'Past4WkDailyLivingImpacted'
# ,'SetBoundariesPrioritiseWellbeing'
# ,'Past4WkDifficultyFindingHousing'
# ,'PrimaryCaregiver'
# ,'Past4WkUseLedToProblemsWithFamilyFriend'
# ,'Past4WkHowOftenPhysicalHealthCausedProblems'
# ,'Past4WkHowOftenMentalHealthCausedProblems'
# ,'Past4WkHowOftenIllegalActivities'
# ,'NeedHelpWrkDevlpmntOrdrPayingOutstndngFines'
# ,'CreatedDatetime'
# ,'Past4WkEngagedInOtheractivities.Paid Work'
# ,'Past4WkEngagedInOtheractivities.Voluntary Work'
# ,'Past4WkEngagedInOtheractivities.Study - college, school or vocational education'
# ,'Past4WkEngagedInOtheractivities.Looking after children'
# ,'Past4WkEngagedInOtheractivities.Other caregiving activities'
# ,'RiskAssessmentChecklist'
# ,'PreferredLanguage'
# ,'CountryOfBirth'
# ,'UsualAccommodation'
# ,'LivingArrangement'
# ,'YourCurrentHousing'
# ,'ChildProtectionConcerns'
# ,'HaveYouServedCustodialSentenceInPast'
# ,'SubjectToCourtOrdersOrPendingCharges'
# ,'HowImportantIsChangeToYou'
# ,'AreYouAccessingOtherServices'
# ,'WhenMentalHealthDiagnosis'
# ,'SupportFromWhichOtherServices'
# ,'ExternalReferrals'
# ,'ChildProtectionDetails'
# ,'Relationship'
# ,'ManagingImpact'
# ,'LegalIssuesDueToOthersUse'
# ,'HowCloseToManagingImpactOfOthersUse'
# ,'OtherAddictiveBehaviours.Porn'
# ,'OtherAddictiveBehaviours.Internet / Social Media'
# ,'MotivationtoQuit'
# ,'CDS5RateAddictiontoCigarettes'
# ,'ReferredFrom'
# ,'DiversityList'
# ,'HowLongSmoked'
# ,'ConfidentQuittingReducing'
# ,'HowManyTimesQuitSmoking'
# ,'HowManagingQuitting'
# ,'HowMuchDoYouKnow'
# ,'QuitlineReferral'
# ,'InterventionType'
# ,'ManagingQuitting'
# ,'OtherAddictiveBehaviours.Gambling'
# ,'CurrentlySmokeYN'
# ,'QuitSmokingBeforeYN'
# ,'IncomeSource'
# ,'CanYouBudgetYN'
# ,'AffordabilityYN'
# ,'MedicalConditions'
# ,'DetailMedicalConditions'
# ,'ManagingPH'
# ,'MedicareNumber'
# ,'PsychiatricHospitalAdmissonYN'
# ,'PTOYN'
# ,'SeeingMHProfessionalYN'
# ,'ManagingMH'
# ,'MHStrategies'
# ,'ChildrenYN'
# ,'ManagingRelations'
# ,'ReportingRequirementsYN'
# ,'BailConditionsYN'
# ,'CorrectiveServsApptsYN'
# ,'IncarceratedAMCYN'
# ,'CriminalRecordYN'
# ,'AVOorFVOYN'
# ,'ICOYN'
# ,'OtherLegalIssuesYN'
# ,'WhereAreYouAt'
# ,'AssistAccessOtherServicesYN'
# ,'ChangeActivities.SelfReflection'
# ,'ChangeActivities.ManagingEmotions'
# ,'ChangeActivities.HealthLiving'
# ,'ChangeActivities.LifestyleChanges'
# ,'ChangeActivities.LifeWithout'
# ,'ChangeActivities.ManageSubstance'
# ,'HealthChecklist_STAFF'
# ,'CSO'
# ,'PublicTrusteeYN'
# ,'question5'
# ,'K5Q2'
# ,'K5Q3'
# ,'K5Q5'
# ,'K5Q4'
# ,'K10CompletedBy'
# ,'SDQP1'
# ,'SDQP2'
# ,'SDQP3'
# ,'SDQP5'
# ,'SDQP6'
# ,'SDQP8'
# ,'SDQP9'
# ,'SDQP10'
# ,'SDQP11'
# ,'SDQP12'
# ,'SDQP13'
# ,'SDQP14'
# ,'SDQP15'
# ,'SDQP16'
# ,'SDQP17'
# ,'SDQP19'
# ,'SDQP20'
# ,'SDQP21'
# ,'SDQP22'
# ,'SDQP24'
# ,'SDQP23'
# ,'SDQP25'
# ,'SDQP18'
# ,'SDQP7'
# ,'question4'
# ,'WhatToWorkOn2'
# ,'SatisfiedwithProgress2'
# ,'OtherAddictiveBehaviours.Gaming'
# ,'ChildCustody'
# ,'FamilyCourtOrdersYN'
# ,'SupervisedVisitYN'
# ,'OtherAddictiveBehaviours.Sex'
# ,'OtherAddictiveBehaviours.Hoarding'
# ,'ConnectionToServices'
# ,'CourtDatesYN'
# ,'CapableManaging'
# ,'K10Q11'
# ,'ConfidenceAlongside'
# ,'SDQ1'
# ,'SDQ2'
# ,'SDQ3'
# ,'SDQ4'
# ,'SDQ5'
# ,'SDQ6'
# ,'SDQ7'
# ,'SDQ8'
# ,'SDQ9'
# ,'SDQ10'
# ,'SDQ11'
# ,'SDQ12'
# ,'SDQ13'
# ,'SDQ14'
# ,'SDQ15'
# ,'SDQ16'
# ,'SDQ17'
# ,'SDQ18'
# ,'SDQ19'
# ,'SDQ20'
# ,'SDQ21'
# ,'SDQ22'
# ,'SDQ23'
# ,'SDQ24'
# ,'SDQ25'
# ,'SDQDifficultiesScore'
# ,'SDQEmotionalProblemsScore'
# ,'SDQConductProblemsScore'
# ,'SDQHyperactivityScore'
# ,'SDQPeerProblemsScore'
# ,'SDQProsocialScore'
# ,'OtherAddictiveBehaviours.Others'
# ,'WhyisitChallenging2'
# ,'Possibilities2'
# ,'WhatCouldGetInTheWay2'
# ,'Alcohol_PerOccassionUse'
# ,'Alcohol_DaysInLast28'
# ,'Heroin_PerOccassionUse'
# ,'Heroin_DaysInLast28'
# ,'Other Opioids_PerOccassionUse'
# ,'Other Opioids_DaysInLast28'
# ,'Cocaine_PerOccassionUse'
# ,'Cocaine_DaysInLast28'
# ,'Cannabis_PerOccassionUse'
# ,'Cannabis_DaysInLast28'
# ,'Amphetamines_PerOccassionUse'
# ,'Amphetamines_DaysInLast28'
# ,'Tranquilliser_PerOccassionUse'
# ,'Tranquilliser_DaysInLast28'
# ,'Another Drug_PerOccassionUse'
# ,'Another Drug_DaysInLast28'
# ,'Nicotine_PerOccassionUse'
# ,'Nicotine_DaysInLast28'
# ,'Gambling_PerOccassionUse'
# ,'Gambling_DaysInLast28']